;; GENERATED by REPL/tools/_liveinventory.py --probe -- do not edit by hand.
;;
;; A DIRTY READ (local call). No gas, no signature, no state change.
;; Paste into any Pact tool pointed at StoaChain and keep the whole output.
;; Feed it back with:  python3 REPL/tools/_liveinventory.py --live SNAPSHOT.txt
;;
;; Asks about 89 module(s) found in this tree.
;; A module that is not deployed answers ABSENT rather than aborting the read --
;; which is the answer being sought for DPMF and EXPLORER.
;;
;; It self-filters through `list-modules`. The first version wrapped each
;; `describe-module` in `try`, which DOES NOT WORK: a missing module raises
;; "Cannot find module", `try` does not catch it, and the whole read aborts on the
;; first absent name -- so the probe would have failed precisely on the modules it
;; exists to ask about. Caught by running it, not by reading it.

(let ((deployed:[string] (list-modules)))
    (map
        (lambda (m:string)
            (if (contains m deployed)
                (let ((d:object (describe-module m)))
                    (format "{} {} {}" [ m, (at "hash" d), (at "interfaces" d) ])
                )
                (format "{} ABSENT" [m])
            )
        )
        [
            "ouronet-ns.AOZ"
            "ouronet-ns.AQP-ANK"
            "ouronet-ns.AQP-BOOT"
            "ouronet-ns.AQP-DSA"
            "ouronet-ns.AQP-FVT"
            "ouronet-ns.AQP-INFO"
            "ouronet-ns.AQP-POOL"
            "ouronet-ns.AQP-SCORE"
            "ouronet-ns.AQP-VCT"
            "ouronet-ns.ATS"
            "ouronet-ns.ATSU"
            "ouronet-ns.BLOODSHED-C"
            "ouronet-ns.BLOODSHED-E"
            "ouronet-ns.BLOODSHED-L"
            "ouronet-ns.BLOODSHED-R"
            "ouronet-ns.BLOODSHED-SETS"
            "ouronet-ns.BRD"
            "ouronet-ns.CADUCEUS"
            "ouronet-ns.CADUCEUS"
            "ouronet-ns.CODEX"
            "ouronet-ns.DALOS"
            "ouronet-ns.DEMIPAD"
            "ouronet-ns.DEMIPAD-CUSTODIANS"
            "ouronet-ns.DEMIPAD-SNAKES"
            "ouronet-ns.DEMIPAD-SPARK"
            "ouronet-ns.DEMIPAD-STOICPAY"
            "ouronet-ns.DPDC"
            "ouronet-ns.DPDC-C"
            "ouronet-ns.DPDC-F"
            "ouronet-ns.DPDC-I"
            "ouronet-ns.DPDC-MNG"
            "ouronet-ns.DPDC-N"
            "ouronet-ns.DPDC-R"
            "ouronet-ns.DPDC-S"
            "ouronet-ns.DPDC-T"
            "ouronet-ns.DPDC-UDC"
            "ouronet-ns.DPL-UR"
            "ouronet-ns.DPMF"
            "ouronet-ns.DPOF"
            "ouronet-ns.DPTF"
            "ouronet-ns.DSP"
            "ouronet-ns.ELITE"
            "ouronet-ns.EQUITY"
            "ouronet-ns.EXPLORER"
            "ouronet-ns.IGNIS"
            "ouronet-ns.INFO-ONE"
            "ouronet-ns.INFO-TWO"
            "ouronet-ns.INFO-ZERO"
            "ouronet-ns.KBN"
            "ouronet-ns.LIQUID"
            "ouronet-ns.MTX-AQP"
            "ouronet-ns.MTX-SWP"
            "ouronet-ns.NOSFERATU"
            "ouronet-ns.OUROBOROS"
            "ouronet-ns.PYTHIA"
            "ouronet-ns.RPS"
            "ouronet-ns.STOAICO"
            "ouronet-ns.SWP"
            "ouronet-ns.SWPI"
            "ouronet-ns.SWPL"
            "ouronet-ns.SWPLC"
            "ouronet-ns.SWPT"
            "ouronet-ns.SWPU"
            "ouronet-ns.TFT"
            "ouronet-ns.TS01-A"
            "ouronet-ns.TS01-C1"
            "ouronet-ns.TS01-C2"
            "ouronet-ns.TS01-C3"
            "ouronet-ns.TS01-C4"
            "ouronet-ns.TS01-CP"
            "ouronet-ns.TS02-C1"
            "ouronet-ns.TS02-C2"
            "ouronet-ns.TS02-C3"
            "ouronet-ns.TS02-CPAD"
            "ouronet-ns.TS02-DPAD"
            "ouronet-ns.U|ATS"
            "ouronet-ns.U|BFS"
            "ouronet-ns.U|CT"
            "ouronet-ns.U|DALOS"
            "ouronet-ns.U|DEC"
            "ouronet-ns.U|DPTF"
            "ouronet-ns.U|G"
            "ouronet-ns.U|INT"
            "ouronet-ns.U|LST"
            "ouronet-ns.U|RS"
            "ouronet-ns.U|ST"
            "ouronet-ns.U|SWP"
            "ouronet-ns.U|VST"
            "ouronet-ns.VST"
        ]
    )
)
