;;<=============================================================================>
;;{0}  ACQUISITION SCHEMAS — the one place every AQP row shape is declared
;;
;; Generated by REPL/tools/_aqpschemas.py. Edit the SCHEMAS here, never a copy.
;;
;; WHY THIS FILE EXISTS
;;   The seven AQP core modules used to declare these 74 schemas between them, 11 of
;;   them twice (RPS and FVT both carried identical copies). A schema that lives in a
;;   module cannot appear in that module's interface, so every function returning one
;;   was locked out of the interface -- 106 of them across the family, unreachable
;;   through a modref. The duplication was a symptom: RPS keeps 10 UDC_ constructors
;;   and declares none of them, so FVT could not call them and copied the shapes.
;;
;;   Hoisting them here is the same shape as DpdcUdcV2 (01_DPDC-UDC.pact), which the
;;   DPDC family already deploys first for exactly this reason.
;;
;; DEPLOY ORDER: this interface loads BEFORE 01_ANK.pact and every AQP module after it.
;;
;; NOT DONE HERE, DELIBERATELY: tables that share a key are NOT merged. Row existence
;;   is used as a boolean signal in this family, so folding a sparse table into a dense
;;   one changes meaning silently. Moving a schema changes no stored bytes; merging a
;;   table changes the data layout. One axis at a time.
;;<=============================================================================>

(namespace "ouronet-ns")

(interface AcquisitionSchemasV1

    ;;<=========================================================================>
    ;;{1}  ANK   — anchors, boost classes, user boost
    ;;      source: 01_ANK.pact
    ;;
    (defschema ANK|Schema
        @doc "General Anchor Definition \
            \ Each Anchor is defined via a so called Anchored-Asset \
            \ This may be a DPTF, DPSF or DPNF; It designation is stored here; \
            \ Along with the Anchor Precision and the Anchor ID itself \
            \ [.]   = fixed, cannot be changed \
            \ [M]   = mutable, can be modified via <CAP_Owner>"
        ank-asset:string            ;;[.]   ID of the the Anchored Asset
        ank-fungibility:[bool]      ;;[.]   Stores the fungibility of the Asset the Anchor is based on.
        boost-class-id:string       ;;[.]   BoostClass this anchor belongs to
        ank-precision:integer       ;;[.]   Precision of the Anchor Variable [min 2 - max 8]
        ank-active:bool             ;;[M]   Stores if the Anchor is active or not. It can be inactivated by revoking it
        ank-promile:decimal         ;;[.]   Promile-value of Anchor
        ;;
        ;;DPTF Anchor ONLY
        dptf-amount:decimal         ;;[.]   DPTF Amount for the defined <promile> [0.0 when not DPTF Anchor]
        ;;
        ;;DPSF Anchor ONLY
        dpsf-nonce:integer          ;;[.]   DPSF Nonce for the defined <promile> [0 when not DPSF Anchor]
        ;;
        ;;DPNF Anchor ONLY
        dpnf-trait-key:string       ;;[.]   DPNF Trait-Key for the defined <promile> [BAR when not DPNF Anchor]
        dpnf-trait-value:string     ;;[.]   DPNF Trait-Value for the defined <promile> [BAR when not DPNF Anchor]
        dpnf-nonce-class:integer    ;;[.]   DPNF Nonce-Class for set anchors [-1 when trait mode, 0 all native NFTs, >0 specific set class]
        ;;
        ;;Select Keys
        anchor-id:string
    )
    (defschema ANK|BoostClass
        @doc "Heterogeneous anchor grouping for score boosting. \
            \ Not tied to any asset-id. Up to 7 anchor slots from different asset types."
        anchor-primary:string       ;;[M]   1st anchor slot
        anchor-secondary:string     ;;[M]   2nd anchor slot
        anchor-tertiary:string      ;;[M]   3rd anchor slot
        anchor-quaternary:string    ;;[M]   4th anchor slot
        anchor-quinary:string       ;;[M]   5th anchor slot
        anchor-senary:string        ;;[M]   6th anchor slot
        anchor-septenary:string     ;;[M]   7th anchor slot
        ;;
        anchors:integer             ;;[M]   Count of active anchors (0-7)
        class-active:bool           ;;[M]   Active flag
        ;;
        ;;Select Keys
        boost-class-id:string       ;;[.]   Self-referential ID
    )
    (defschema ANK|InternalGroup
        @doc "Nested schema for ANK|AssetAnchors group slots (not a table). Up to 7 anchor slots per group."
        anchor-primary:string
        anchor-secondary:string
        anchor-tertiary:string
        anchor-quaternary:string
        anchor-quinary:string
        anchor-senary:string
        anchor-septenary:string
        anchors:integer             ;;Count within this group (0-7)
    )
    (defschema ANK|AssetAnchors
        @doc "Tracks all anchors for one asset-id. 7 internal groups x 7 slots = 49 cap. \
            \ Single read gives all anchor-ids for an asset."
        group-primary:object{ANK|InternalGroup}
        group-secondary:object{ANK|InternalGroup}
        group-tertiary:object{ANK|InternalGroup}
        group-quaternary:object{ANK|InternalGroup}
        group-quinary:object{ANK|InternalGroup}
        group-senary:object{ANK|InternalGroup}
        group-septenary:object{ANK|InternalGroup}
        ;;
        groups-active:integer       ;;[M]   Groups in use (0-7)
        anchors-active:integer      ;;[M]   Total anchors across all groups (0-49)
        ;;
        ;;Select Keys
        asset-id:string             ;;[.]   Self-referential asset-id
    )
    (defschema ANK|UserSchema
        @doc "Stores the cumulate promile of a given <ouronet-account> for a given <anchor-id> \
            \ [.]   = fixed, cannot be changed \
            \ [M]   = mutable, can be modified via <ouronet-account> Ownership"
        promile:decimal             ;;[M]   Promile of User with Anchor
        ;;
        ;;Select Keys
        ouronet-account:string      ;;[.]   Stores the Ouronet Account for which the Anchor Value is saved
        anchor-id:string            ;;[.]   Stores the Anchor-ID
    )
    (defschema ANK|UserBoostSchema
        @doc "Aggregate promile for one user across all anchors in one BoostClass. \
            \ Eagerly updated whenever any member anchor promile changes for this user."
        aggregate-promile:decimal   ;;[M]   Sum of user promiles across member anchors
        ;;
        ;;Select Keys
        ouronet-account:string      ;;[.]   User account
        boost-class-id:string       ;;[.]   BoostClass reference
    )
    (defschema ANK|BoostClassScoreLinks
        @doc "Key = <Boost-Class-ID>. The SET of SCORE ids whose boost-class-link references this class — the H4 \
            \ REVERSE INDEX (sweep phase 1): enumerable (the re-score sweep walks it to find every score/position \
            \ an anchor change touches) AND the #9 revoke lock (the class's anchors are locked while the set is \
            \ non-empty). AQP-SCORE maintains it in XI_CreateBoostClassLink: add on link, remove on re-point/unlink. \
            \ The lock count = (length score-links) — this set is the single source of truth."
        score-links:[string]
        boost-class-id:string
    )

    ;;<=========================================================================>
    ;;{2}  SCORE — scores, per-asset score definitions, triplets
    ;;      source: 02_SCORE.pact
    ;;
    (defschema SCR|Schema
        @doc "General Score Definition \
            \ [.]   = fixed, cannot be changed \
            \ [..]  = Once linked, cannot be changed \
            \ [.t]  = Once set to true, cannot be changed \
            \ [M]   = mutable, can be modified  <owner-konto> \
            \ [Mu]  = mutable via upgrade, can be modified via \
            \        <owner-konto> and true <can-upgrade> \
            \ \
            \ Identity: No separate scr-asset on the score. Staking asset is \
            \ defined on the AQP pool. Resolve Score -> aqpool-link -> Pool \
            \ -> asset-id. FVT must only add ScoreLink when aqpool-link is \
            \ set, so membership checks (e.g. farm common-denominator vs LP \
            \ construction) use that chain. \
            \ \
            \ Class-0 LP: One score employed per pool aggregates all stake \
            \ that pool allows. Multiple token ids (e.g. native LP, sleeping \
            \ OF, frozen TF) may stake into the same pool when the protocol \
            \ verifies they are the same LP family; trackers distinguish ids, \
            \ but SCR|T|UserScore rows are per pool-id x score-id for \
            \ beneficiaries. \
            \ \
            \ Immutability vs users: Per-user weights in SCR|T|UserScore are \
            \ advanced on Stake/Unstake (and FVT Inject/Collect handle \
            \ rewards), matching the UrStoa vault pattern; there is no \
            \ practical global recomputation over all accounts. Do not change \
            \ [.] semantic fields (score-class, multipliers, sft/nft models), \
            \ links [..], or deb-boost [.t] after positions \
            \ exist; that would leave existing rows wrong until users \
            \ restake. Correct mistakes by issuing a new score-id, removing \
            \ the old score from pool slots and FVT membership, then wiring \
            \ the new score. \
            \ \
            \ [M] totals on this row are aggregate bookkeeping; they do not \
            \ replace the rule that meaning-of-weight is fixed by [.] fields \
            \ at issue."
        ;;
        ;;Management
        owner-konto:string          ;;[Mu]  Stores the Score Owner.
        can-upgrade:bool            ;;[Mu]  Defines if Score Settings can be upgraded
        can-change-owner:bool       ;;[Mu]  Defines if the Owner can be changed
        ;;
        ;; Links
        boost-class-link:string     ;;[..]  Specifies the BoostClass-ID for boosting. BAR if not in use.
        ;; Foreign boost-link: promile uses linked score user base; UserScore boosted/deb may hold surplus only (README_SCORE.md). Never self: SCR|C>CREATE-BOOST-LINK-SCORE.
        boost-link:string           ;;[..]  BAR = own base for promile; else other score-id (≠ this score-id per SCR|C>CREATE-BOOST-LINK-SCORE).
        aqpool-link:string          ;;[..]  Specifies the Pool that employs the Score. BAR if not in use.
        fvt-link:string             ;;[..]  Specifies the FVT the Score is part of. BAR if not in use.
        triplet:bool                ;;[..]  false at issue; true once bundled in SCR|T|Triplet (immutable).
        triplet-id:string           ;;[..]  BAR until triplet issue; then T|bronze|silver|golden (immutable).
        ;;Score Information
        deb-boost:bool              ;;[.t]  Specifies if DEB boosting occurs.
        precision:integer           ;;[.]   Decimal places for per-user weights and aggregate total-* fields on this score; range enforced at issuance; forward writers must respect it.
        total-base-score:decimal    ;;[M]   Sum of user base-scores; same decimal precision as precision field
        total-boosted-score:decimal ;;[M]   Sum of user boosted-scores; same decimal precision as precision field
        total-deb-score:decimal     ;;[M]   Sum of user deb-scores; same decimal precision as precision field
        total-base-deb-score:decimal    ;;[M] M3: Σ user base-deb-scores (aggregate base×deb decomposition)
        total-boosted-deb-score:decimal ;;[M] M3: Σ user boosted-deb-scores. total-base-deb + total-boosted-deb = total-deb-score.
        nzs-count:integer           ;;[M]   Store the amount of Non-Zero-Scores
        vacate-generation:integer   ;;[M]   Vacate-v2 lazy-invalidation counter (§5). Bumped once at fast-vacate
        ;;                                  finalize (nuke). A SCR|T|UserScore row whose stamped-generation < this
        ;;                                  reads as 0 (stale); re-stake stamps the current value. Default 0.
        ;;
        ;;Score Class
        score-class:integer         ;;[.]   Defines the Score Class, there are 5
        ;;                                  Class 0 = LP Score (LP - native|sleeping|freezing)
        ;;                                  Class 1 = DPTF Score (non LP) 
        ;;                                  Class 2 = DPOF Score (non LP)
        ;;                                  Class 3 = DPSF Score (SFTs)
        ;;                                  Class 4 = DPNF Score (NFTs)
        ;;
        ;;LP, DPTF, DPOF
        lp-denominator:string       ;;[.]   Class-0 only: native DPTF token-id of the common pool leg (e.g. OURO-98c486052a51); BAR for classes 1-4.
        mx-frozen:decimal           ;;[.]   Multiplier for Frozen Tokens (Default 2.0)
        mx-sleeping:decimal         ;;[.]   Multiplier for Sleeping Tokens (Default 1.0)
        mx-hibernated:decimal       ;;[.]   Multiplier for Hibernated Tokens (Default 1.0)
        ;;
        ;;DPSF
        sft-equality:bool           ;;[.]   When true all SFTs are equal. When <false>, <nonce-score-value> is checked.
        ;;
        ;;DPNF
        nft-score-model:integer     ;;[.]   Sets NFT Score Model; Only 3 Models Allowed [-1 0 1]
        ;;                                  Model -1 = All NFTs are equal, and will have a score of 1
        ;;                                  Model  0 = NFTs will be scored by their native Score Systems
        ;;                                  Model  1 = NFTs scored from SCR|T|NF|TraitScore / SCR|T|NF|ClassScore rows
        ;;
        ;;Select Keys
        score-id:string             ;;[.]   Stores the ID of the Score
    )
    (defschema SCR|UserSchema
        @doc "Per account x pool x score. base-score, boosted-score, \
            \ deb-score are updated on Stake/Unstake (and related paths), \
            \ not by bulk recompute when SCR|Schema rules change; migrate \
            \ via a new score-id."
        base-score:decimal
        boosted-score:decimal
        deb-score:decimal
        base-deb-score:decimal      ;;[M]  M3: base × deb (deb applied to the base part)
        boosted-deb-score:decimal   ;;[M]  M3: boost × deb (deb applied to the boost part). base-deb + boosted-deb = deb-score.
        stamped-generation:integer  ;;[M]  Vacate-v2 (§5): the SCR|Schema.vacate-generation this row was written under.
        ;;                                 When < the score's current vacate-generation, readers treat this row as 0
        ;;                                 (stale after a fast-vacate); a fresh stake re-stamps it live. Default 0.
        ;;
        ;;Select Keys
        ouronet-account:string
        pool-id:string
        score-id:string
    )
    (defschema SCR|SingularUserScoreDelta
        @doc "Result of applying one signed user-base delta at score precision: new user triple, nz-count delta, and deltas to SCR|T|Score aggregate totals \
            \ (LP stake legs are one consumer; other forward paths can reuse the same derivation object). Aggregate totals are floored at the score precision field in XI."
        new-user-base-score:decimal
        new-user-boosted-score:decimal
        new-user-deb-score:decimal
        new-user-base-deb-score:decimal
        new-user-boosted-deb-score:decimal
        nz-delta:integer
        delta-global-base-score:decimal
        delta-global-boosted-score:decimal
        delta-global-deb-score:decimal
        delta-global-base-deb-score:decimal
        delta-global-boosted-deb-score:decimal
    )
    (defschema SCR|SF|Schema
        @doc "Per (score-id, dpsf-id, nonce). Changing nonce-score-value \
            \ changes weights for that nonce going forward; wholesale rule \
            \ changes still favor a new score-id if fairness requires it."
        nonce-score-value:decimal   ;;[M]   Score Value of DPSF Nonce
        ;;
        ;;Select Keys
        score-id:string
        dpsf-id:string
        nonce:integer
    )
    (defschema SCR|NF|TraitSchema
        @doc "Per (score-id, dpnf-id, trait-key, trait-value). trait-score-value is mutable."
        trait-score-value:decimal   ;;[M]
        ;;
        ;;Select Keys
        score-id:string
        dpnf-id:string
        trait-key:string
        trait-value:string
    )
    (defschema SCR|NF|ClassSchema
        @doc "Per (score-id, dpnf-id, dpnf-nonce-class). trait-score-value is mutable (set-mode class weights)."
        trait-score-value:decimal   ;;[M]
        ;;
        ;;Select Keys
        score-id:string
        dpnf-id:string
        dpnf-nonce-class:integer    ;;[.]   0 = all native NFTs in class model; >0 = specific set class (AQP-ANK DPNF anchors)
    )
    (defschema SCR|SF|DefRevision
        @doc "Per (score-id, dpsf-id). revision-nonce bumps on any add or \
            \ update in SCR|T|SF|Score for that score-id and dpsf-id."
        revision-nonce:integer      ;;[M]   Bump on SCR|T|SF|Score change
        ;;
        ;;Select Keys
        score-id:string
        dpsf-id:string
    )
    (defschema SCR|NF|DefRevision
        @doc "Per (score-id, dpnf-id). global-revision-nonce bumps on any trait or class definition change; \
            \ trait-revision-nonce only on SCR|T|NF|TraitScore change; class-revision-nonce only on SCR|T|NF|ClassScore change."
        global-revision-nonce:integer   ;;[M]
        trait-revision-nonce:integer    ;;[M]
        class-revision-nonce:integer     ;;[M]
        ;;
        ;;Select Keys
        score-id:string
        dpnf-id:string
    )
    (defschema SCR|NF|TraitKeys
        @doc "Per (score-id, dpnf-id): the DISTINCT trait-keys with any SCR|T|NF|TraitScore definition. Lets model-1 \
            \ trait scoring point-read each defined key against a staked nonce's metadata instead of scanning."
        trait-keys:[string]         ;;[M]   distinct defined trait-keys
        ;;
        ;;Select Keys
        score-id:string
        dpnf-id:string
    )
    (defschema SCR|Triplet
        @doc "Key = T|<bronze-score-id>|<silver-score-id>|<golden-score-id>. Bundles three SCORE rows for FVT TripletLink membership. \
            \ Positions bronze/silver/golden are id slots only (not boost roles). true-triplet when one score has BAR boost-link and the other two boost-link to it. \
            \ Tags: [.] fixed at issue."
        bronze-score-id:string                               ;;[.]   First score id slot
        silver-score-id:string                               ;;[.]   Second score id slot
        golden-score-id:string                               ;;[.]   Third score id slot
        triplet-category:string                              ;;[.]   LP | VAULT_TF | TREASURY_SF_NF (from shared score-class)
        triplet-id:string                                    ;;[.]   Select key T|bronze|silver|golden
        true-triplet:bool                                    ;;[.]   Boost-anchored bundle (one BAR hub, two satellites)
    )
    (defschema SCR|ScoreEntityModel
        @doc "Key = <Model-ID>. A reusable score-entity TEMPLATE so many entities issue IDENTICALLY (DSA: every \
            \ agency scores the same). single (entity-type 1): the scoring spec — issue 1 score + its SF definition \
            \ from it. triplet (entity-type 3): references three single model-ids — issue the 3 singles, then \
            \ C_IssueTriplet. Tags: [.] fixed at define."
        entity-type:integer                                  ;;[.]   CT_SCORE_MODEL_SINGLE (1) | CT_SCORE_MODEL_TRIPLET (3)
        score-class:integer                                  ;;[.]   single: 3 = SemiFungible (DPSF), v1 SF only. triplet: 0.
        collectable-id:string                                ;;[.]   single: the DPSF id the definition scores. triplet: BAR.
        precision:integer                                    ;;[.]   single: score precision. triplet: 0.
        nonces:[integer]                                     ;;[.]   single: SF definition nonces (incl. fragment negatives). triplet: [].
        nonce-score-values:[decimal]                         ;;[.]   single: parallel values. triplet: [].
        bronze-model-id:string                               ;;[.]   triplet: the 3 sub single-model ids. single: BAR.
        silver-model-id:string
        golden-model-id:string
        ;;Select Keys
        model-id:string                                      ;;[.]
    )

    ;;<=========================================================================>
    ;;{3}  AQP   — pools, per-fungibility trackers, beneficiary totals
    ;;      source: 03_AQP.pact
    ;;
    (defschema AQP|Schema
        @doc "One aqp-class and one canonical asset-id per pool; employed \
            \ scores must match that class. Staking asset identity is \
            \ authoritative here (SCORE: Score -> aqpool-link -> this pool \
            \ -> asset-id). Class 0: asset-id is the primary LP key; stake \
            \ paths may accept additional linked LP token ids (native / \
            \ sleeping OF / frozen TF) when verified as the same LP family; \
            \ all credit the same pool score slots. Fix wrong pool economics \
            \ by issuing a new pool and new scores, not by mutating class or \
            \ primary asset-id after stake exists."
        ;;
        aqp-class:integer                                       ;;Defines the Pool Class, there are 5
        ;;                                                        Class 0 = LP family pool (issue native LP; stake native|F||Z| LP)
        ;;                                                        Class 1 = DPTF family pool (issue native DPTF; stake native|F| + linked sleep/hib DPOF)
        ;;                                                        Class 2 = standalone DPOF (issue one dpof; no sleep/hib satellites — use class 0/1)
        ;;                                                        Class 3 = DPSF collection pool
        ;;                                                        Class 4 = DPNF collection pool
        asset-id:string                                         ;;ID of the Asset that is allowed to be staked in the Pool.
        ;;                                                        This must be in accordance with the <aqp-class> and together with it
        ;;                                                        Defines which assets can be staked in the Pool
        ;;
        ;;Score - Links
        score-primary:string
        score-secondary:string
        score-tertiary:string
        score-quaternary:string
        score-quinary:string
        score-senary:string
        score-septenary:string
        ;;
        stake-enabled:bool                                      ;;[M]   Gates new stakes when false; default true at issue. Unstake/vacate ignore.
        vacate-in-progress:bool                                 ;;[M]   True while AQP-VCT session active on this pool.
        sweep-in-progress:bool                                  ;;[M]   True while a re-score sweep (anchor retire/re-price) runs; blocks stake + collect (D3).
        nns:integer                                             ;;[M]   #FP1: number of OCCUPIED nonce positions in the pool tracker (occupancy oracle,
        ;;                                                        counts ghost nonces that nzs misses). -1 for amount-based pools (class 0/1, N/A);
        ;;                                                        0 at issue for nonce-based pools (class 2/3/4). +1 on a position going empty->occupied,
        ;;                                                        -1 on occupied->empty (last amount removed). Finalize uses nns==0 for nonce pools.
        ;;
        ;;Select Keys
        aqp-id:string
    )
    (defschema AQP|TrueFungibleTracker
        balance:decimal                                         ;;Store DPTF Balance Amount
        ;;
        ;;Select Keys
        pool-id:string                                          ;;Pool-ID
        dptf-id:string                                          ;;DPTF-ID
        owner-id:string                                         ;;Owner-ID
        beneficiary-id:string                                   ;;Beneficiary-ID
    )
    (defschema AQP|OrtoFungibleTracker
        balance:decimal                                         ;;Staked DPOF amount for this nonce slot
        ;;
        ;;Select Keys
        pool-id:string                                          ;;Pool-ID
        dpof-id:string                                          ;;DPOF-ID
        owner-id:string                                         ;;Owner-ID
        beneficiary-id:string                                   ;;Beneficiary-ID
        nonce:integer                                           ;;Nonce-Value
    )
    (defschema AQP|SemiFungibleTracker
        @doc "DPSF custody: staked balance per pool, collection, owner, beneficiary, nonce."
        balance:decimal                                         ;;Stores DPSF Balance
        ;;
        ;;Select Keys
        pool-id:string                                          ;;Pool-ID
        dpsf-id:string                                          ;;DPSF-ID
        owner-id:string                                         ;;Owner-ID
        beneficiary-id:string                                   ;;Beneficiary-ID
        nonce:integer                                           ;;Nonce-Value
    )
    (defschema AQP|NonFungibleTracker
        @doc "DPNF custody: staked balance per pool, collection, owner, beneficiary, nonce."
        balance:decimal                                         ;;Stores DPNF Balance
        ;;
        ;;Select Keys
        pool-id:string                                          ;;Pool-ID
        dpnf-id:string                                          ;;DPNF-ID
        owner-id:string                                         ;;Owner-ID
        beneficiary-id:string                                   ;;Beneficiary-ID
        nonce:integer                                           ;;Nonce-Value
    )
    (defschema AQP|BenDptfTotal
        @doc "Cross-pool rollup: total DPTF staked by one beneficiary on one exact dptf-id leg \
            \ (native X and F|X are separate rows). Maintained on every TF stake/unstake POOL leg \
            \ (FVT::CC_TrueFungibleStakeFlow → XE_TrueFungible* legs → XI bump). Input to \
            \ ANK::XE_UpdateTrueFungibleUserAnchorValues without scanning AQP|T|DPTFTracker keys. \
            \ last-ank-sync-count stores AQP-ANK::UR_AA|AnchorsActive(dptf-id) after the last successful \
            \ anchor refresh; URC_BenDptfAnchorsNeedSync compares it to the live count so the UI can \
            \ prompt C_SyncTrueFungibleAnchors when new anchors are issued after stake. Per-pool detail \
            \ remains in AQP|T|DPTFTracker; this row is the single O(1) read for anchor promile."
        total-balance:decimal                                           ;;[M] Sum of tracker balances for (beneficiary, dptf-id) across all pools
        last-ank-sync-count:integer                                     ;;[M] ANK AssetAnchors.anchors-active at last C_Sync* / stake ANK leg (0 = never synced)
        ;;
        ;;Select Keys
        beneficiary-id:string                                           ;;[.] Beneficiary (SCORE/ANK ouronet-account)
        dptf-id:string                                                  ;;[.] Exact DPTF id leg (native or F|); must match ANK ank-asset for sync call
    )
    (defschema AQP|BenDpsfNonceTotal
        @doc "Cross-pool per-nonce DPSF rollup for one beneficiary. Separate table from DPNF so SELECT inventory \
            \ does not scan NFT rows. Maintained on DPSF stake/unstake POOL legs (phase 1.3, planned). amount is \
            \ integer supply staked on that nonce across all pools; 0 means fully unstaked (row may remain)."
        amount:integer                                                  ;;[M] Staked supply on this nonce (0 = no active stake)
        ;;
        ;;Select Keys
        beneficiary-id:string                                           ;;[.] Beneficiary (SCORE/ANK ouronet-account)
        dpsf-id:string                                                  ;;[.] DPSF collection id (ANK ank-asset for SF sync)
        nonce:integer                                                   ;;[.] DPSF nonce
    )
    (defschema AQP|BenDpnfNonceTotal
        @doc "Cross-pool per-nonce DPNF rollup for one beneficiary. Separate table from DPSF — same id string may \
            \ exist on both collections when minted in one tx, but rows live in disjoint tables. Maintained on DPNF \
            \ stake/unstake POOL legs (phase 1.3, planned)."
        amount:integer                                                  ;;[M] Staked supply on this nonce (0 = no active stake)
        ;;
        ;;Select Keys
        beneficiary-id:string                                           ;;[.]
        dpnf-id:string                                                  ;;[.] DPNF collection id
        nonce:integer                                                   ;;[.] DPNF nonce
    )
    (defschema AQP|BenDpsfAnkMeta
        @doc "Per (beneficiary, dpsf-id) ANK sync metadata. last-ank-sync-count is leg-wide, not per nonce — \
            \ mirrors AQP|BenDptfTotal for TF. active-nonce-count is O(1) has-stake for defcaps (no select). \
            \ Bumped when BenDpsfNonceTotal crosses 0↔positive; preserved on sync stamp."
        last-ank-sync-count:integer                                     ;;[M] ANK AssetAnchors.anchors-active at last sync (0 = never)
        active-nonce-count:integer                                      ;;[M] Count of BenDpsfNonceTotal rows with amount > 0
        ;;
        ;;Select Keys
        beneficiary-id:string                                           ;;[.]
        dpsf-id:string                                                  ;;[.]
    )
    (defschema AQP|BenDpnfAnkMeta
        @doc "Per (beneficiary, dpnf-id) ANK sync metadata — DPNF counterpart of AQP|BenDpsfAnkMeta."
        last-ank-sync-count:integer                                     ;;[M] ANK AssetAnchors.anchors-active at last sync (0 = never)
        active-nonce-count:integer                                      ;;[M] Count of BenDpnfNonceTotal rows with amount > 0
        ;;
        ;;Select Keys
        beneficiary-id:string                                           ;;[.]
        dpnf-id:string                                                  ;;[.]
    )
    (defschema AQP|UserOccupancy
        @doc "Vacate-v2 §4: per (pool, beneficiary) occupancy — the count of this beneficiary's OCCUPIED \
            \ tracker positions in the pool (nonce rows for class 2/3/4; the single TF leg contributes 1 for \
            \ class 1). Maintained alongside the pool nns on every tracker 0<->occupied transition (stake / \
            \ unstake / vacate-drain). The fast-vacate drain settles a beneficiary exactly once, the moment \
            \ this hits 0 (their last position drained). Point-readable so the drain never scans tracker keys."
        unn:integer                                                     ;;[M] User-Nonces-in-pool: occupied tracker positions for this beneficiary
        ;;
        ;;Select Keys
        pool-id:string                                                  ;;[.] Pool
        beneficiary-id:string                                           ;;[.] Beneficiary (SCORE / reward recipient)
    )

    ;;<=========================================================================>
    ;;{4}  RPS   — reward engine: global/member/user/stream ledgers
    ;;      source: 04_RPS.pact
    ;;
    (defschema FVT|RPS|Global
        @doc "Key = <FVT-ID> | <DPTF-ID>. One registered reward DPTF on this FVT."
        reward-enabled:bool
        current-rps:decimal
        available-rewards:decimal
        unclaimed-count:integer
        ;; Escrow-on-empty (zombie/limbo): reward tokens injected while the inject denominator is 0 (no stakers)
        ;; are held here — physically in AQP|SC_NAME custody, counted, but NOT yet routed into G / available-rewards.
        ;; The next inject at a NON-zero denominator adds this on top of its amount, distributes the sum to whoever
        ;; is staked at that instant (pro-rata via G / farm-split), and zeroes it. Kept OUT of available-rewards so
        ;; the M1 last-claimant dust sweep can never pay a prior cohort the pending escrow. No owner reclaim: it
        ;; stays until a normal non-zero inject flushes it.
        zombie-rewards:decimal
        segmentation:bool
        reward-kind:string                                      ;;[.]   PLAIN | MULTIPLET_BASE
        multiplet-family-id:string                              ;;[.]   BAR or F|t0|t1|t2
        ;; Time-streamed inject (linear vesting) — the lane's active-stream ledger cursor. stream-count = live
        ;; stream positions (0 = none; the drip fast-returns). stream-last-release = shared lane checkpoint (every
        ;; active stream's start <= this, since a new stream is only added AFTER a drip). stream-unreleased =
        ;; custodied-but-not-yet-dripped total (held in AQP|SC_NAME, kept OUT of available-rewards / the M1 sweep
        ;; until the drip releases it). See Audit/STREAMED-INJECT-DESIGN.md.
        stream-count:integer
        stream-last-release:time
        stream-unreleased:decimal
        ;; DSA royalty pool: the uptime-shortfall slice of a delegation inject that no agency captured
        ;; (Σ capture-units − Σ effective capture-weight, worth A×that/Σunits). Custodied in AQP|SC_NAME, kept
        ;; OUT of available-rewards / G / the M1 sweep until the owner disposes it (withdraw / burn / fuel).
        ;; Always 0.0 on a non-delegation lane (Σ capture-weight == Σ capture-units ⇒ no shortfall).
        royalty-rewards:decimal
        ;;
        ;;Select Keys
        fvt-id:string
        dptf-id:string
    )
    (defschema FVT|RPS|Member
        @doc "Key = <FVT-ID> | <Score-Entity-ID> | <DPTF-ID>. Member reward line per score-entity × reward DPTF."
        last-farm-rps-g:decimal
        member-deb-rps:decimal
        pending-member-rewards:decimal
        ;;
        ;;Select Keys
        fvt-id:string
        score-entity-id:string
        dptf-id:string
    )
    (defschema FVT|RPS|User
        @doc "Key = <User-ID> | <FVT-ID> | <Score-Entity-ID> | <DPTF-ID>. Per-staker row."
        last-rps:decimal
        pending-rewards:decimal
        user-id:string
        fvt-id:string
        score-entity-id:string
        dptf-id:string
    )
    (defschema FVT|RPS|Stream
        @doc "Key = <FVT-ID> | <DPTF-ID> | <position 1..49>. One live linear-release stream on a reward lane. \
            \ Positions are kept COMPACT (occupied = 1..stream-count); a finished stream is pruned and later \
            \ positions shift down. UI renders position n as tier-style major.minor (major = ceil(n/7), \
            \ minor = ((n-1) mod 7) + 1). rate = amount/duration (token-per-second, high precision); finish = \
            \ block-time the stream stops; amount = original streamed amount; released = cumulative released so \
            \ far, so the finish drip flushes (amount - released) and per-stream conservation is exact."
        rate:decimal
        finish:time
        amount:decimal
        released:decimal
        ;;
        ;;Select Keys
        fvt-id:string
        dptf-id:string
        position:integer
    )
    (defschema FVT|MemberVault
        @doc "Key = <FVT-ID> | <Score-Entity-ID> | <DPTF-ID> (base ATS token). The per-member mini-vault for the \
            \ Tier-1 dust sweep (M1 / #10): available-rewards = rewards routed to this member (farm split-at-inject \
            \ slice, or vault Tier-2 earned) minus what its users have been paid; unclaimed-count = users in this \
            \ member with a live claim. When unclaimed-count hits 1, the member's last user is paid available-rewards \
            \ (sweeping the member's floor dust). Mirrors FVT|RPS|Global's available-rewards/unclaimed-count one tier down."
        available-rewards:decimal
        unclaimed-count:integer
        ;;
        ;;Select Keys
        fvt-id:string
        score-entity-id:string
        dptf-id:string
    )
    (defschema FVT|MemberUserWeight
        @doc "Key = <User-ID> | <FVT-ID> | <Score-Entity-ID>. Farm-triplet per-user Level-1 weight snapshot — \
            \ w-user (Σ lanes) as of the user's last score stake/unstake. Summed into \
            \ ScoreEntityLink.total-lane-weight and used as the user's Tier-1 numerator, so numerator and \
            \ divisor share one snapshot basis (reward conservation), exactly like a singular score uses \
            \ stored deb-score + maintained total-deb-score."
        contrib-weight:decimal
        ;;
        ;;Select Keys
        user-id:string
        fvt-id:string
        score-entity-id:string
    )
    (defschema FVT|ForcedFixCount
        @doc "Key = <FVT-ID> | <DPTF-ID> | <User-ID>. M3 #12 2e penalty: how many of this user's stale scores an \
            \ enforced inject (CC_Inject / MTX|n|C_Inject) FORCE-fixed on this reward lane since the user last \
            \ collected it. At collect the user pays `count × RATE` NON-discountable IGNIS (a gas reimbursement — \
            \ the inject did N fixes for him; reward paid is untouched) and the count is zeroed. Self-fixing at \
            \ collect (PHASE 6 backstop) does NOT bump this — only inject-forced fixes do, so self-fixing stays \
            \ the cheaper path."
        count:integer
        ;;
        ;;Select Keys
        fvt-id:string
        dptf-id:string
        user-id:string
    )
    (defschema FVT|RewardAggregate
        @doc "Key = <FVT-ID>. Reward-computation aggregates split out of FVT|Schema (#75 B' Stage 1) so \
            \ the reward orchestration owns them; identity/config stays in FVT|Schema."
        fvt-class:integer                                       ;;[.]   0=Farm · 1=Vault · 2=Treasury (moved here #75 B' Stage 2)
        owner-konto:string                                      ;;      entity owner (moved #75 B' Stage 2b)
        mosaic:bool                                             ;;[Mu]  mix score + triplet entities when true
        membership-mode:string                                  ;;[Mu]  BAR | SCORE | TRUE-TRIPLET | STANDARD-TRIPLET
        split-mode:string                                       ;;[M]   Farm reward-split: SPLIT|STAKED | SPLIT|TVL
        total-ghost-tvl-weight:decimal                          ;;[M]   Farm S = sum enabled ScoreEntityLink W_i
        total-base-score:decimal
        total-boosted-score:decimal
        total-deb-score:decimal
        total-nzs-count:integer
        enabled-reward-count:integer
        member-link-count:integer                               ;;[M]   ScoreEntityLink rows (gates C_SetMosaic)
        ;;Select Keys
        fvt-id:string
    )
    (defschema FVT|ScoreEntityLink
        @doc "Key = <FVT-ID> | <Score-Entity-ID>. Unified membership — score (type 1) or triplet (type 3)."
        score-entity-type:integer                               ;;[.]   CT_SCORE_ENTITY_SCORE=1, CT_SCORE_ENTITY_TRIPLET=3
        enabled:bool                                            ;;[M]
        swpair:string                                           ;;[..]
        ghost-tvl-weight:decimal                                ;;[M]   Level-2 W_i (SWP staked value)
        total-lane-weight:decimal                               ;;[M]   Farm-triplet Level-1 divisor Σ w-user;
        ;;                                                              snapshot-maintained at stake/unstake (phase 4.6),
        ;;                                                              point-read as the L_i divisor (no staker scan).
        ;; DSA (Delegated Staking Agencies) — set only for a delegation member (= an agency); default
        ;; false/0.0/0.0/EPOCH for every normal member. DSA maintains them (delegator stake/unstake + the daily
        ;; oracle) via an XE_; FVT only ever READS its own fields at inject (dependency DSA -> FVT). See
        ;; Audit/DSA-DELEGATED-STAKING-DESIGN.md §3.
        delegation:bool                                         ;;[M]   is this member a DSA agency?
        capture-units:decimal                                   ;;[M]   ideal capacity = min(floor(Q/unit-score), nodes) — the IDEAL denominator term
        capture-weight:decimal                                  ;;[M]   actual = capture-units × uptime/1000 — the inject NUMERATOR
        oracle-ts:time                                          ;;[M]   timestamp of the last oracle write (now − ts > 25h ⇒ effective capture 0)
        ;;
        ;;Select Keys
        fvt-id:string                                           ;;[.]
        score-entity-id:string                                  ;;[.]   score-id or triplet-id T|…
    )
    (defschema FVT|MultipletFamily
        @doc "Key = F|<token-0-id>|<token-1-id>|<token-2-id>. Reward ladder for MULTIPLET_BASE collect."
        token-0-id:string
        token-1-id:string
        token-2-id:string
        ats-0-1-id:string
        ats-1-2-id:string
        rank:integer                                            ;;[.]   Lane count at issue (v1 = 3)
        active:bool
        ;;
        ;;Select Keys
        multiplet-family-id:string
    )
    (defschema FVT|UserPresence
        @doc "Key = <FVT-ID> | <Ouronet-ID>. Membership marker (M3 #12 / shared with the H4 anchor sweep): \
            \ is-present = true while the user holds a live position (nonzero weight) in AT LEAST ONE of this \
            \ FVT's score-entities. Written true (add-only) on every stake; recomputed to false on the unstake \
            \ that drops the user's LAST position in the FVT. Maintained for ALL FVT classes. Lets a sweep \
            \ enumerate one FVT's users with a single `select` over a small purpose-built table (no giant \
            \ RPS|User scan). A stale `true` is harmless — the sweep no-ops on a zero-weight user."
        is-present:bool
        ;;
        ;;Select Keys
        fvt-id:string
        ouronet-id:string
    )
    (defschema FVT|AgencyFee
        @doc "Key = <FVT-ID> | <Score-Entity-ID>. DSA operator fee for a delegation member (the agency), mirrored \
            \ from DSA|Agency so the FVT inject settle can read it locally (FVT can't reach DSA). At inject the \
            \ member-slice is split: the delegator-facing index L_i advances by member-slice·(1−fee) (so ALL \
            \ stakers accrue net), and the whole member-slice·fee is credited DIRECTLY to the operator's pending — \
            \ giving the operator its own weighted share + the fee (effective weight own + fee·Σdelegators), \
            \ delegators (1−fee), conserved. The fee is never baked into a stored weight, so a fee change is O(1) \
            \ (it only reprices the NEXT inject). Set by DSA at open + C_SetAgencyFee."
        operator-konto:string
        fee-per-mille:integer
    )
    (defschema FVT|QualitySplit
        @doc "Key = <FVT-ID> | <DPTF-ID> (same as RPS|Global). Round B: the per-FVT reward MODE + heterogeneous \
            \ split MATRIX for a MULTIPLET_BASE triplet reward. HOMOGENEOUS ⇒ each lane routes to its one ladder \
            \ token (bronze→t0, silver→t1, gold→t2) — the default when this row is absent. HETEROGENEOUS ⇒ each \
            \ lane splits across ALL 3 ladder tokens per its row [to-t0 to-t1 to-t2] (per-mille, sums to 1000): \
            \ bronze-split for the bronze lane, silver-split for silver, gold-split for gold. Per-FVT-reward + \
            \ owner-tunable (unlike the chain-wide immutable FVT|MultipletFamily ladder)."
        mode:string                                             ;;[M]   HOMOGENEOUS | HETEROGENEOUS
        bronze-split:[integer]                                  ;;[M]   [to-t0 to-t1 to-t2] per-mille, sums 1000
        silver-split:[integer]                                  ;;[M]
        gold-split:[integer]                                    ;;[M]
        ;;Select Keys
        fvt-id:string
        dptf-id:string
    )
    (defschema FVT|DsaOracleConfig
        @doc "Single GLOBAL row (key = FVT|DSA-ORACLE-KEY). The protocol-wide DSA external-oracle switch + validity \
            \ window, replacing the per-FVT oracle-on + the DSA_ORACLE_TTL constant. `external-oracle` = is external \
            \ oracling on at all: ON ⇒ a delegation member captures its weight only while its last oracle write is \
            \ fresher than `oracle-validity` seconds (no/stale entry ⇒ effective 0); OFF ⇒ oracling is bypassed \
            \ entirely and the stored capture-weight is trusted as-is. Read lazily (defaults: on=true, \
            \ validity=DSA_ORACLE_TTL) so no init is needed; written only by A_ToggleExternalOracle / \
            \ A_SetOracleValidity (DSA module admin) via the FVT XE_ setters."
        external-oracle:bool
        oracle-validity:integer
    )
    (defschema FVT|ScorePreNzFlag
        @doc "Pre-SCORE snapshot for one employed score."
        score-id:string
        was-nz:bool
    )
    (defschema FVT|SettleFvtRewards
        @doc "One distinct FVT row in URH_FVT|SettleFvtRewardBundle."
        fvt-id:string
        reward-dptf-ids:[string]
    )
    (defschema FVT|SettleScorePlan
        @doc "One score-entity row in URC_SettleScorePlanRows — entity + fvt + reward list."
        score-entity-type:integer
        score-entity-id:string
        fvt-id:string
        reward-dptf-ids:[string]
    )
    (defschema FVT|MemberPreDeb
        @doc "Pre-SCORE live deb-weight snapshot for one settled member (M2/#11 incremental total-deb mirror). \
            \ Self-describing (carries its keys) so no positional alignment with settle-plans is needed."
        fvt-id:string
        score-entity-type:integer
        score-entity-id:string
        pre-deb:decimal
    )
    (defschema FVT|StakeSettleBundle
        @doc "Precomputed stake/unstake settle scope."
        settle-scores:[string]
        distinct-fvts:[string]
        settle-plans:[object{FVT|SettleScorePlan}]
        pre-nz-flags:[object{FVT|ScorePreNzFlag}]
        pre-member-debs:[object{FVT|MemberPreDeb}]
    )

    ;;<=========================================================================>
    ;;{5}  FVT   — farms, vaults, treasuries
    ;;      source: 05_FVT.pact
    ;;
    (defschema FVT|Schema
        @doc "Key = <FVT-ID>. One farm, vault, or treasury (FVT) entity: class, owner, enabled-reward-count, SCORE aggregate mirrors. \
            \ Farm (fvt-class 0): common-denominator + total-ghost-tvl-weight S is inject denominator. \
            \ Vault/Treasury: total-deb-score mirror for inject; common-denominator sentinel \"|\"; total-ghost-tvl-weight 0.0. \
            \ UrStoa analogue: vault header (urstoa-supply on SCORE side; S or total-deb here is FVT-side denominator). \
            \ Field tags: [.] fixed at issue; [..] fixed once set; [M] mutable; [Mu] mutable only under owner + can-upgrade."
        can-upgrade:bool
        can-change-owner:bool
        common-denominator:string                               ;;[Mu]  unsafe to change after ScoreEntityLinks
        oracle-on:bool                                          ;;[M]   DSA: node/uptime oracle governs capture. Default false.
        ;; fvt-class, owner-konto, mosaic, membership-mode, split-mode + the reward aggregates
        ;; live in FVT|RewardAggregate (#75 B' Stage 1/2) — the reward engine reads/owns them.
        ;;Select Keys
        fvt-id:string
    )
    (defschema FVT|VacateFreeze
        @doc "Key = <FVT-ID>. True while a pool this FVT serves is mid-vacate — blocks collect + inject on the FVT \
            \ so the owner-forced vacate is not interfered with (stake/unstake are frozen pool-side via \
            \ PoolVacateInProgress). Set by AQP-VCT begin (XI_EnsureVacateBegun) on each of the vacating pool's \
            \ employed-score FVTs; cleared by VCT finalize. Read via UR_FVT|VacateFrozen (with-default-read false)."
        frozen:bool
    )
    (defschema FVT|SweepProgress
        @doc "Key = <Anchor-ID>. Cursor for the paginated defun+gate re-score sweep (CC_SweepBegin → \
            \ CCp_SweepRecomputeChunk*), the scalable twin of the fixed 2-step MTX|2|C_SweepRevokeAnchor defpact. \
            \ `total` = the recompute-set size captured at BEGIN (sweep-in-progress freeze holds URH_FvtPresentUsers \
            \ fixed across the batch's separate txs); `offset` = holders recomputed so far over the GLOBAL flattened \
            \ present set (present users concatenated across the boost-class's score-ids in order); `active` = a \
            \ sweep is open. The finalizing chunk (win-hi reaches total) unfreezes every affected pool + clears \
            \ active — completeness is ENFORCED (pools cannot unfreeze until offset reaches total). Read via \
            \ UR_FVT|SweepProgress / UR_FVT|SweepActive (with-default-read inactive)."
        total:integer
        offset:integer
        active:bool
    )

    ;;<=========================================================================>
    ;;{6}  VCT   — vacate planning
    ;;      source: 06_VCT.pact
    ;;
    (defschema VCT|SlicePayload
        @doc "Vacate slice payload for plan OC and hash commitment. \
            \ TF (vacate-asset-kind=1): amounts populated; nonces-array and amounts-array empty. \
            \ OF/DPSF/DPNF: nonces-array + amounts-array populated; amounts empty. \
            \ OF uses zero-sentinel amounts-array; collectables use full tracker balances per nonce."
        pool-id:string
        asset-id:string
        vacate-asset-kind:integer
        owner-ids:[string]
        beneficiary-ids:[string]
        amounts:[decimal]
        nonces-array:[[integer]]
        amounts-array:[[integer]]
    )
    (defschema VCT|VacateSlicePlan
        @doc "Offline Legs split plan — full slice payloads for UI (no on-chain job writes). \
            \ vacate-job-id is unused under Legs (always \"\")."
        vacate-job-id:string
        pool-id:string
        asset-id:string
        vacate-asset-kind:integer
        slice-count:integer
        slices:[object{VCT|SlicePayload}]
    )
    (defschema VCT|VacateTfLeg
        owner-id:string
        beneficiary-id:string
        balance:decimal
    )
    (defschema VCT|VacateNonceRow
        owner-id:string
        beneficiary-id:string
        nonce:integer
        balance:decimal
    )
    (defschema VCT|VacateNonceLeg
        owner-id:string
        beneficiary-id:string
        nonces:[integer]
        amounts:[decimal]
    )
    (defschema VCT|VacateTfInventory
        @doc "UI pre-flight bundle: TF vacate legs + leg-count."
        legs:[object{VCT|VacateTfLeg}]
        leg-count:integer
    )
    (defschema VCT|VacateNonceLegInventory
        @doc "UI pre-flight bundle: grouped nonce vacate legs + leg-count."
        legs:[object{VCT|VacateNonceLeg}]
        leg-count:integer
    )
    (defschema VCT|VacateTfLane
        @doc "One DPTF asset-lane of a pool + its TF vacate legs (PHASE-1 scan output; consumed per asset)."
        asset-id:string
        legs:[object{VCT|VacateTfLeg}]
    )
    (defschema VCT|VacateNonceLane
        @doc "One DPOF/DPSF/DPNF asset-lane of a pool + its nonce vacate legs (PHASE-1 scan output)."
        asset-id:string
        legs:[object{VCT|VacateNonceLeg}]
    )

    ;;<=========================================================================>
    ;;{7}  DSA   — delegated staking agencies
    ;;      source: 08_DSA.pact
    ;;
    (defschema DSA|Template
        @doc "Key = <FVT-ID>. Per DSA vault: binds a class-0 FVT to the score-entity MODEL every agency \
            \ instantiates (SCR|ScoreEntityModel) + the unit-score (1 staking unit = 1 node; open gate = \
            \ unit-score/2). The model fixes the scoring (Custodians nonce→quintessence) so all agencies are comparable."
        model-id:string                                         ;;[.]   the SCR|ScoreEntityModel agencies instantiate (SCORE)
        unit-score:integer                                      ;;[.]   quintessence per capture unit (e.g. 20000)
        active:bool                                             ;;[M]
        ;;Select Keys
        fvt-id:string
    )
    (defschema DSA|Agency
        @doc "Key = <FVT-ID> | <Score-Entity-ID>. One agency = one FVT member (its triplet). Operator is an \
            \ ownership role independent of stake; fee is skimmed from delegators only. nodes + uptime are the \
            \ oracle inputs to the capture transform (the derived capture-units/weight live on the FVT member)."
        operator-konto:string                                   ;;[..]  the agency operator (runs nodes, takes the fee)
        fee-per-mille:integer                                   ;;[M]   flat fee 10..500 (= 1%..50%) on delegators
        nodes:integer                                           ;;[M]   oracle: nodes the operator runs (capture cap)
        uptime:integer                                          ;;[M]   oracle: promile 1..1000 (1000 = full)
        ;;Select Keys
        fvt-id:string
        score-entity-id:string
    )
    (defschema DSA|OracleAuth
        @doc "Key = <FVT-ID>. The FVT-owner-delegated key allowed to write the daily {nodes, uptime} oracle values \
            \ for every agency on this vault."
        oracle-guard:guard                                      ;;[M]
        ;;Select Keys
        fvt-id:string
    )

)
