#!/usr/bin/env python3
"""Ask the CHAIN what is deployed, and diff it against this tree.

WHY THIS EXISTS. Four separate decisions are blocked on the same unknown -- "what is actually
live?" -- and this repository cannot answer it: there is no network from the build environment,
and `Deploy/` is generated from LOCAL sources, so it happily describes a redeploy of a module
that is already newer on chain.

    DPMF        does it exist on Stoa at all? (decides read-only retirement vs leave-alone)
    BLOODSHED   does live differ from this source? (decides refactor scope)
    NOSFERATU   same
    DPL-UR      the owner may have deployed reads DIRECTLY, never committing them here --
                shipping the local copy would then REGRESS live functionality
    EXPLORER    does it exist at all?

and the general case, which matters for every round: **which modules in this tree differ from
the chain**, so a "full redeploy" ships what changed rather than what someone guessed changed.
The current round is scoped on `git log` since a snapshot date. That is a good proxy. A hash is
not a proxy.

USAGE
    python3 REPL/tools/_liveinventory.py --probe OUT.pact     write the paste-ready dirty read
    python3 REPL/tools/_liveinventory.py --live SNAPSHOT.txt  diff a returned snapshot vs tree

THE PROBE IS A *LOCAL* CALL -- a dirty read. It costs no gas, needs no signature, and changes
nothing. Paste it into any Pact tool pointed at StoaChain and keep the output.

Each module is wrapped in `try`, so a module that does NOT exist reports "ABSENT" instead of
aborting the whole read. That is the entire point for DPMF and EXPLORER, where absence IS the
answer being sought.

SNAPSHOT FORMAT -- one module per line, `#` and blanks ignored:

    DALOS      ouronet-ns.DALOS      <hash>   OuronetDalosV2,OuronetPolicyV2
    DPMF       ABSENT

which is what the probe prints.
"""
import os, re, sys, json

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TOPS = ("1_SOVEREIGN", "2_CITIZEN")
NS = "ouronet-ns"

MOD_RE = re.compile(r'^\(module\s+([^\s()]+)', re.M)
IMPL_RE = re.compile(r'^\s*\(implements\s+([^\s()]+)\)', re.M)


def tree_modules():
    """[(module-name, relpath, [implemented interfaces])] for every module in the tree."""
    out = []
    for top in TOPS:
        for d, _, fs in os.walk(os.path.join(ROOT, top)):
            if os.sep + "Audit" in d + os.sep:
                continue
            for f in sorted(fs):
                if not f.endswith(".pact"):
                    continue
                p = os.path.join(d, f)
                src = open(p, encoding="utf8", errors="replace").read()
                for m in MOD_RE.finditer(src):
                    out.append((m.group(1), os.path.relpath(p, ROOT), sorted(set(IMPL_RE.findall(src)))))
    return sorted(out)


def write_probe(dest):
    mods = tree_modules()
    names = [m[0] for m in mods]
    L = [
        ";; GENERATED by REPL/tools/_liveinventory.py --probe -- do not edit by hand.",
        ";;",
        ";; A DIRTY READ (local call). No gas, no signature, no state change.",
        ";; Paste into any Pact tool pointed at StoaChain and keep the whole output.",
        ";; Feed it back with:  python3 REPL/tools/_liveinventory.py --live SNAPSHOT.txt",
        ";;",
        f";; Asks about {len(names)} module(s) found in this tree.",
        ";; A module that is not deployed answers ABSENT rather than aborting the read --",
        ";; which is the answer being sought for DPMF and EXPLORER.",
        ";;",
        ";; It self-filters through `list-modules`. The first version wrapped each",
        ";; `describe-module` in `try`, which DOES NOT WORK: a missing module raises",
        ";; \"Cannot find module\", `try` does not catch it, and the whole read aborts on the",
        ";; first absent name -- so the probe would have failed precisely on the modules it",
        ";; exists to ask about. Caught by running it, not by reading it.",
        "",
        "(let ((deployed:[string] (list-modules)))",
        "    (map",
        "        (lambda (m:string)",
        "            (if (contains m deployed)",
        "                (let ((d:object (describe-module m)))",
        '                    (format "{} {} {}" [ m, (at "hash" d), (at "interfaces" d) ])',
        "                )",
        '                (format "{} ABSENT" [m])',
        "            )",
        "        )",
        "        [",
    ]
    for n in names:
        L.append(f'            "{NS}.{n}"')
    L += ["        ]", "    )", ")", ""]
    open(dest, "w", encoding="utf8").write("\n".join(L))
    print(f"wrote {dest} -- dirty read over {len(names)} module(s)")
    print("Run it against StoaChain, save the output, then:")
    print(f"  python3 REPL/tools/_liveinventory.py --live SNAPSHOT.txt")
    return 0


def read_snapshot(path):
    live = {}
    for raw in open(path, encoding="utf8"):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        line = line.strip('"').strip("[],")
        if not line:
            continue
        parts = line.split(None, 2)
        if len(parts) < 2:
            continue
        name = parts[0].split(".")[-1]
        if parts[1].upper() == "ABSENT":
            live[name] = None
        else:
            ifaces = parts[2] if len(parts) > 2 else ""
            live[name] = (parts[1], [x.strip(' []",') for x in ifaces.replace(",", " ").split() if x.strip(' []",')])
    return live


def diff(path):
    live = read_snapshot(path)
    mods = tree_modules()
    absent, missing_snapshot, iface_drift, present = [], [], [], []
    for name, rel, ifaces in mods:
        if name not in live:
            missing_snapshot.append((name, rel))
        elif live[name] is None:
            absent.append((name, rel))
        else:
            present.append((name, rel))
            lifaces = {i.split(".")[-1] for i in live[name][1]}
            tifaces = set(ifaces)
            if lifaces != tifaces:
                iface_drift.append((name, rel, sorted(tifaces - lifaces), sorted(lifaces - tifaces)))
    print(f"live inventory -- {len(mods)} module(s) in tree, {len(live)} answered\n")
    if absent:
        print(f"  NOT DEPLOYED ({len(absent)}) -- these exist only here:")
        for n, r in absent:
            print(f"     {n:22s} {r}")
    if iface_drift:
        print(f"\n  INTERFACE DRIFT ({len(iface_drift)}) -- tree and chain disagree:")
        for n, r, only_tree, only_live in iface_drift:
            print(f"     {n:22s} {r}")
            if only_tree:
                print(f"         tree-only: {', '.join(only_tree)}")
            if only_live:
                print(f"         LIVE-only: {', '.join(only_live)}  <-- live has something the tree lacks")
    if missing_snapshot:
        print(f"\n  NOT IN SNAPSHOT ({len(missing_snapshot)}) -- probe is stale, regenerate it:")
        for n, r in missing_snapshot:
            print(f"     {n:22s} {r}")
    if not (absent or iface_drift or missing_snapshot):
        print("  tree and chain agree on existence and interfaces.")
    print("\n  NOTE: a matching interface list does NOT mean matching CODE. Only the module")
    print("  hash says that, and comparing it needs the hash of what WE would deploy, which")
    print("  only `pact` can compute. Interface drift is the cheap check, not the whole one.")
    return 0


def main():
    if "--probe" in sys.argv:
        return write_probe(sys.argv[sys.argv.index("--probe") + 1])
    if "--live" in sys.argv:
        return diff(sys.argv[sys.argv.index("--live") + 1])
    print(__doc__)
    print("\nNothing to do. Pass --probe OUT.pact or --live SNAPSHOT.txt.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
