#!/usr/bin/env python3
"""_pricesync.py -- the generated IGNIS pricing artefacts must equal what the generators emit.

WHY THIS EXISTS (2026-09-15)
----------------------------
`OuronetInformational/IGNIS-PRICING/IGNIS-PRICE-SHEET.md` and `IGNIS-DETER-WORKSHEET.md` are
GENERATED documents, and the price sheet is the input to the Chapter-2 documentation. Nothing
checked that either file still matched its generator. Two things followed:

  1. The 2026-09-14 tools move (`REPL/*.py` -> `REPL/tools/*.py`) left BOTH generators dead --
     they resolved a sibling by a hard-coded `REPL/_letfix.py` / `REPL/_ignis_deter_worksheet.py`
     path and raised FileNotFoundError at import. Eleven tools in total. Nothing noticed, because
     nothing ran them.
  2. While dead, the artefacts were HAND-EDITED -- their `Generated by` / `Regenerate:` lines were
     updated to the new `REPL/tools/...` path. The provenance line of a document that could not be
     regenerated was corrected to name a command that crashed. Meanwhile the worksheet still
     carried the PRE-X-04 names (`C_WipeHeavy`, `A_RemoveSecondary`, `C_BreakSemiFungibleSet`),
     stale by a 126-replacement rename, under a header asserting the two sheets "cannot drift".

The rule this enforces is the one already in `_gate.py`'s comment, applied to a second directory:
a number an audit document publishes must be one the gate RE-DERIVES on every run.

`--check`     regenerate both artefacts in memory, diff against the committed files, exit 1 on drift
`--write`     regenerate and overwrite the committed files
`--selftest`  prove the checker fails on drift and passes on a match
"""
import os, sys, subprocess, difflib

HERE = os.path.dirname(os.path.abspath(__file__))            # REPL/tools
ROOT = os.path.dirname(os.path.dirname(HERE))                # repo root

ARTEFACTS = [
    ("_ignis_price_sheet.py",      "OuronetInformational/IGNIS-PRICING/IGNIS-PRICE-SHEET.md"),
    ("_ignis_deter_worksheet.py",  "OuronetInformational/IGNIS-PRICING/IGNIS-DETER-WORKSHEET.md"),
]


def generate(tool):
    """Run a generator from the REPO ROOT (its globs are repo-relative) and return stdout."""
    r = subprocess.run([sys.executable, os.path.join(HERE, tool)],
                       capture_output=True, text=True, cwd=ROOT)
    if r.returncode != 0:
        raise RuntimeError(f"{tool} failed to run:\n{r.stderr.strip()[:2000]}")
    return r.stdout


def legend_vs_table(sheet_text):
    """Every op the sheet's own EXEMPT legend names must be published as free in its own table.

    2026-09-15: line 22 of IGNIS-PRICE-SHEET.md read "EXEMPT -- deliberately free: ... the IGNIS
    machinery itself (the collectors, Compress/Sublimate/Firestarter, DalosFuel)" while line 557
    published `C_Firestarter` at **>= 93** COMPLEX. The document contradicted itself 535 lines
    apart, and nothing compared the two halves. Derived from the legend text rather than a retyped
    list, so a new exempt name is covered the day it is added.
    """
    import re as _re
    m = _re.search(r'\*\*EXEMPT\*\*(.{0,400}?)\n\n', sheet_text, _re.S)
    if not m:
        return ["could not find the EXEMPT legend paragraph in the price sheet"]
    names = set(_re.findall(r'[A-Z][A-Za-z]{3,}', m.group(1)))
    bad = []
    for w in sorted(names):
        row = _re.search(r'^\| `C_' + _re.escape(w) + r'[A-Za-z]*` \|[^|]*\|[^|]*\| \*\*([^*]+)\*\* \|',
                         sheet_text, _re.M)
        if row and row.group(1).strip() != "0":
            bad.append(f"the EXEMPT legend names '{w}' as deliberately free, but the table "
                       f"publishes C_{w}... at {row.group(1).strip()}")
    return bad


NARRATIVE = "OuronetInformational/IGNIS-PRICING/IGNIS-PRICING.md"


def narrative_tally(sheet_text):
    """The prose doc quotes the sheet's headline tally. Re-derive it and compare.

    The artefacts being regenerable is not enough on its own: IGNIS-PRICING.md is the document
    the owner reads, and on 2026-09-15 it still said "Nothing on pricing. Every one of the 420
    Talos client functions now carries a price", quoting 182/190/10/48 -- figures no longer
    produced by anything, asserting a completeness the generator's own silent `skipped` counter
    contradicted. A generated artefact guarded by the gate, quoted by a narrative nobody checks,
    just moves the stale number one file along.
    """
    import re
    m = re.search(r'(\d+) simple \(exact price\) . (\d+) complex \(floor price\) . '
                  r'(\d+) STOA-only . (\d+) exempt . (\d+) unresolved . (\d+) unpriced '
                  r'. (\d+) Talos client functions', sheet_text)
    if not m:
        return ["could not find the tally line in the generated price sheet"]
    simple, complex_, stoa, exempt, unres, unpriced, total = m.groups()
    want = (f"{simple} exact  \u00b7  {complex_} floor  \u00b7  {stoa} STOA-only  \u00b7  "
            f"{exempt} exempt  \u00b7  {unres} unresolved  \u00b7  {unpriced} unpriced")
    have = open(os.path.join(ROOT, NARRATIVE)).read()
    bad = []
    if want not in have:
        bad.append(f"{NARRATIVE} does not quote the sheet's tally.\n"
                   f"       expected line: {want}")
    if f"**{total}**" not in have:
        bad.append(f"{NARRATIVE} does not quote the sheet's Talos client-function total ({total})")
    return bad


def check(write=False, quiet=False):
    drift = 0
    for tool, rel in ARTEFACTS:
        path = os.path.join(ROOT, rel)
        try:
            fresh = generate(tool)
        except RuntimeError as e:
            print(f"DEAD GENERATOR: {e}")
            drift += 1
            continue
        have = open(path).read() if os.path.exists(path) else ""
        if write:
            open(path, "w").write(fresh)
            if not quiet:
                print(f"  wrote {rel}")
            continue
        if have != fresh:
            drift += 1
            d = list(difflib.unified_diff(have.splitlines(), fresh.splitlines(),
                                          fromfile=rel + " (committed)",
                                          tofile=rel + " (regenerated)", lineterm="", n=0))
            print(f"\nDRIFT: {rel} -- {len([x for x in d if x[:1] in '+-' and x[:3] not in ('+++','---')])} line(s)")
            for line in d[:60]:
                print("   " + line[:200])
            if len(d) > 60:
                print(f"   ... {len(d)-60} more diff lines")
        elif not quiet:
            print(f"  ok  {rel}")
    # the narrative doc must quote the artefact, not a memory of it
    if not write:
        try:
            _sheet = generate(ARTEFACTS[0][0])
            for _bad in legend_vs_table(_sheet):
                drift += 1
                print(f"\nDRIFT: {_bad}")
            for _bad in narrative_tally(_sheet):
                drift += 1
                print(f"\nDRIFT: {_bad}")
        except RuntimeError as e:
            drift += 1; print(f"DEAD GENERATOR: {e}")
        if not quiet and drift == 0:
            print(f"  ok  {NARRATIVE} (quotes the sheet's tally)")

    if drift and not write:
        print(f"\n{drift} generated pricing artefact(s) do not match their generator."
              f"\nRegenerate with:  python3 REPL/tools/_pricesync.py --write")
    return drift


def selftest():
    """A checker nobody has seen fail is not evidence. Prove both directions."""
    ok = True
    rel = ARTEFACTS[0][1]
    path = os.path.join(ROOT, rel)
    original = open(path).read()
    try:
        # 1. clean tree must pass
        if check(quiet=True) != 0:
            print("SELFTEST FAIL: clean tree reported drift"); ok = False
        else:
            print("  selftest 1/2: clean tree passes                     OK")
        # 2. perturb one published number -- must be caught
        bad = original.replace("| **≥ 1000** |", "| **≥ 1001** |", 1)
        if bad == original:
            bad = original.rstrip("\n") + "\nstray line\n"
        open(path, "w").write(bad)
        import io, contextlib
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            n = check(quiet=True)
        if n == 0:
            print("SELFTEST FAIL: a perturbed published figure was NOT caught"); ok = False
        else:
            print("  selftest 2/2: perturbed figure is caught             OK")
    finally:
        open(path, "w").write(original)
    return 0 if ok else 1


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(selftest())
    if "--write" in sys.argv:
        sys.exit(1 if check(write=True) else 0)
    # `--check` must never mutate. The first cut of this line read
    #     check("--check" in sys.argv)
    # which passed write=True whenever --check was given, so the "verify" mode SILENTLY
    # REWROTE the artefacts and always reported success. A checker that resolves drift by
    # overwriting it is worse than no checker: it is a green light wired to nothing.
    sys.exit(1 if check(write=False) else 0)
