#!/usr/bin/env python3
"""Is the registry snapshot still what the CHAIN says? Ask the chain.

THE GAP THIS CLOSES. `OURONET-REGISTRY.json` is generated by `_registry.py`, which reads the chain.
Two checks then guard it, and both compare the artefact to something that is not the chain:

    _pkgsync.py            artefact  <->  the copy bundled in @ouronet/talos-registry
    sync-registry.mjs      the same comparison, from the package's side

So after a deploy the artefact simply stays as it was generated, both checks report "in sync", the
package ships a stale surface, and every consumer validates against it. `sync-registry.mjs`'s own
header names the hazard exactly -- "consumers would validate against it and get confident wrong
answers" -- and then guards the copy rather than the content. Nothing asked the chain again.

That matters more now than when the artefact was first generated. Three things are derived from it:
OuronetUI's execution tooltips (409 specs), `ouronet-core`'s builder-arity test, and the ghost
values every preview is fired with. A stale snapshot does not make those fail -- it makes them
agree with each other about the wrong surface.

HOW. Every entrypoint in the artefact carries the `moduleHash` it was read from, and a Pact module
hash changes on any redeploy. So one `describe-module` per distinct module -- twelve calls -- is a
complete answer, not a sample. A matching hash means the source behind every entrypoint of that
module is byte-identical to what was described when the snapshot was taken.

    python3 REPL/tools/_registrylive.py            report, exit 1 on drift
    python3 REPL/tools/_registrylive.py --record   also write the sidecar the gate reads

NOT IN THE GATE, deliberately. The gate must run offline -- `_registry.py --check` is offline and
fatal for that reason. This needs the network, so it is a post-deploy step. `--record` writes
`Deploy/OURONET-REGISTRY.livecheck.json` so the offline gate can at least print WHEN the snapshot
was last confirmed against mainnet, which is a fact rather than a guess.
"""
import base64
import datetime
import hashlib
import io
import json
import os
import sys
import time
import urllib.error
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
REGISTRY = os.path.join(ROOT, "Deploy", "OURONET-REGISTRY.json")
SIDECAR = os.path.join(ROOT, "Deploy", "OURONET-REGISTRY.livecheck.json")
NODE = ("https://node2.stoachain.com/chainweb/0.0/stoa/chain/0/pact/api/v1/local"
        "?preflight=false&signatureVerification=false")


def rpc(code):
    cmd = json.dumps({
        "networkId": "stoa", "payload": {"exec": {"data": {}, "code": code}}, "signers": [],
        "meta": {"gasLimit": 10_000_000, "chainId": "0", "gasPrice": 1e-8, "sender": "",
                 "ttl": 600, "creationTime": int(time.time()) - 60},
        "nonce": str(time.time())}, separators=(",", ":"))
    digest = hashlib.blake2b(cmd.encode(), digest_size=32).digest()
    body = json.dumps({"cmd": cmd,
                       "hash": base64.urlsafe_b64encode(digest).decode().rstrip("="),
                       "sigs": []}).encode()
    req = urllib.request.Request(NODE, data=body, headers={"Content-Type": "application/json"})
    # A transport failure is NOT drift. Reported separately, because "the node was unreachable"
    # and "the module was redeployed" call for opposite actions.
    for attempt in range(3):
        try:
            result = json.load(urllib.request.urlopen(req, timeout=60)).get("result", {})
            break
        except (urllib.error.URLError, TimeoutError, ConnectionError) as exc:
            if attempt == 2:
                return ("TRANSPORT", str(exc)[:110])
            time.sleep(2 * (attempt + 1))
    if result.get("status") == "success":
        return ("OK", result.get("data"))
    return ("ERR", str((result.get("error") or {}).get("message", "?"))[:160])


def expected():
    """module -> the single moduleHash the artefact recorded for it.

    A module with TWO hashes would mean the artefact was assembled across a redeploy -- itself a
    defect, and one this function must not average away. Reported rather than collapsed.
    """
    doc = json.load(io.open(REGISTRY, encoding="utf8"))
    per = {}
    for key, entry in doc["entrypoints"].items():
        h = entry.get("moduleHash")
        if not h:
            continue
        per.setdefault(key.split(".")[0], set()).add(h)
    split = {m: sorted(v) for m, v in per.items() if len(v) > 1}
    return {m: sorted(v)[0] for m, v in per.items()}, split, doc.get("surfaceHash")


def main():
    if not os.path.exists(REGISTRY):
        sys.exit(f"no registry artefact at {REGISTRY} -- run _registry.py first.")
    want, split, surface = expected()
    if not want:
        sys.exit("the artefact carries no moduleHash at all -- this check would pass over "
                 "nothing. Regenerate it with _registry.py.")
    if split:
        print("!! the artefact records MORE THAN ONE hash for a module -- it was assembled "
              "across a redeploy:")
        for m, hashes in split.items():
            print(f"   {m}: {', '.join(h[:16] + '…' for h in hashes)}")

    drift, unreachable, live = [], [], {}
    for module, snapshot in sorted(want.items()):
        status, value = rpc(f'(at "hash" (describe-module "ouronet-ns.{module}"))')
        if status == "TRANSPORT":
            unreachable.append((module, value))
            print(f"  unreachable {module:12} {value}")
            continue
        if status != "OK":
            drift.append((module, snapshot, None))
            print(f"  GONE        {module:12} describe-module failed: {value}")
            continue
        live[module] = value
        if value == snapshot:
            print(f"  ok          {module:12} {snapshot[:16]}…")
        else:
            drift.append((module, snapshot, value))
            print(f"  DRIFTED     {module:12} snapshot={snapshot[:16]}… live={value[:16]}…")

    print(f"\n{len(want)} module(s) behind {surface}: {len(want) - len(drift) - len(unreachable)} "
          f"current, {len(drift)} drifted, {len(unreachable)} unreachable")

    if "--record" in sys.argv and not drift and not unreachable:
        io.open(SIDECAR, "w", encoding="utf8").write(json.dumps({
            "note": "WHEN the registry snapshot was last confirmed against mainnet, by "
                    "REPL/tools/_registrylive.py. Written only on a clean run. The offline gate "
                    "prints this date; it cannot verify it.",
            "verifiedAt": datetime.date.today().isoformat(),
            "surfaceHash": surface,
            "moduleHashes": live,
        }, indent=1, sort_keys=True) + "\n")
        print(f"recorded in {os.path.relpath(SIDECAR, ROOT)}")

    if drift:
        print("\nA drifted module was REDEPLOYED after the snapshot was taken. Everything derived "
              "from the artefact now describes the old surface and agrees with itself about it: "
              "OuronetUI's 409 execution specs, ouronet-core's builder-arity test, and every "
              "ghost value. Regenerate with `python3 REPL/tools/_registry.py`, then re-sync the "
              "package (`npm run sync` in talos-registry) and regenerate the UI's specs.")
        return 1
    if unreachable:
        print("\nNo drift found, but some modules could not be reached -- rerun before trusting "
              "this as a clean result.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
