#!/usr/bin/env python3
"""Emit Deploy/TALOS-ABI.json -- the callable surface of the protocol, for every consumer.

WHY THIS IS GENERATED HERE AND NOT WRITTEN THERE.  Three consumers -- OuronetUI, the Codex
package, Pythia -- each hardcode Pact function names and argument orders as strings.  Each one
drifted independently, and every drift was found by a user rather than by a test: 30 cost
previews calling `MODULE|INFO_Action` after the contracts moved to `INFO_MODULE|Action`, five
pool-management builders one argument short after the patron/executor sweep,
`UR_AccountKadena` after the Kadena->Stoa rename, a hibernated-nonce reader that made Awake and
Slumber report "no nonces" against three live ones.

A missing member is a RESOLUTION error, so `try` cannot catch it and consumers render it as a
default -- which is why every one of these looked like missing DATA rather than a broken call,
and why they survived so long.

The fix is not to correct the copies.  It is to stop copying: consumers supply VALUES, the ABI
supplies NAMES, ORDER and TYPES, and a rename becomes one regeneration instead of N
archaeologies.  Generated from the sources and diffed by the gate, so a contract rename that is
not carried into the ABI fails HERE, before it can reach a consumer.

    python3 REPL/tools/_talosabi.py --write    regenerate
    python3 REPL/tools/_talosabi.py --check    diff, fatal inside _gate.py
"""
import hashlib
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "Deploy", "TALOS-ABI.json")

# Talos is the only supported client path (MODULE_ARCHITECTURE.md), so its `|C_` / `|CC_`
# entrypoints are the whole callable surface. `INFO_` previews come too -- a consumer that can
# call an operation should be able to price it, and pairing them here is what lets a UI render
# a cost without hardcoding a second name.
ENTRYPOINT = re.compile(r'^[A-Za-z0-9|_-]*\|C{1,2}p?_[A-Za-z0-9]+$')
PREVIEW = re.compile(r'^INFO_[A-Za-z0-9|_-]+$')


def params_at(text, idx):
    """[(name, type)] for the defun whose name ends at `idx`, across line breaks."""
    i = text.index("(", idx)
    depth, j = 0, i
    while j < len(text):
        if text[j] == "(":
            depth += 1
        elif text[j] == ")":
            depth -= 1
            if depth == 0:
                break
        j += 1
    block = text[i:j + 1]
    return [{"name": m.group(1), "type": m.group(2)}
            for m in re.finditer(r'([a-z][A-Za-z0-9-]*)\s*:\s*([A-Za-z0-9\[\]{}.|_-]+)', block)]


def scan():
    out = {}
    for base, _dirs, files in os.walk(ROOT):
        if os.sep + "Deploy" in base or os.sep + "REPL" in base:
            continue
        for fn in files:
            if not fn.endswith(".pact"):
                continue
            text = io.open(os.path.join(base, fn), encoding="utf8", errors="replace").read()
            for mod in re.finditer(r'^\(module\s+([A-Za-z0-9|_-]+)\s', text, re.M):
                body = text[mod.start():]
                for d in re.finditer(r'\n\s{1,8}\(defun\s+([^\s:(]+)', body):
                    name = d.group(1)
                    if not (ENTRYPOINT.match(name) or PREVIEW.match(name)):
                        continue
                    key = f"{mod.group(1)}.{name}"
                    if key in out:
                        continue
                    out[key] = params_at(body, d.end())
    return out


def pair_previews(sigs):
    """Match each entrypoint to its INFO_ preview, where one exists.

    `TS01-C2.ATS|C_Coil` -> `INFO-ONE.INFO_ATS|Coil`. The pairing is by CATEGORY and ACTION, not
    by module, because the two live in different modules by design -- and because assuming they
    share one is how a consumer ends up calling `INFO-ZERO` for a preview that lives on
    `INFO-ONE`.
    """
    previews = {}
    for key in sigs:
        mod, fn = key.split(".", 1)
        m = re.match(r'^INFO_([A-Za-z0-9-]+)\|(.+)$', fn)
        if m:
            previews[(m.group(1), m.group(2))] = key
    paired = {}
    for key in sigs:
        mod, fn = key.split(".", 1)
        m = re.match(r'^([A-Za-z0-9-]+)\|C{1,2}p?_(.+)$', fn)
        if m:
            hit = previews.get((m.group(1), m.group(2)))
            if hit:
                paired[key] = hit
    return paired


def build():
    sigs = scan()
    entry = {k: v for k, v in sigs.items() if ENTRYPOINT.match(k.split(".", 1)[1])}
    prev = {k: v for k, v in sigs.items() if PREVIEW.match(k.split(".", 1)[1])}
    doc = {
        "note": "GENERATED by REPL/tools/_talosabi.py from the Pact sources. Do not edit. "
                "Consumers supply values; this supplies names, order and types.",
        "namespace": "ouronet-ns",
        "entrypoints": dict(sorted(entry.items())),
        "previews": dict(sorted(prev.items())),
        "previewFor": dict(sorted(pair_previews(sigs).items())),
    }
    # A fingerprint of the surface itself, so a consumer can tell it is holding a stale ABI
    # rather than silently calling last month's names -- staleness being the whole failure mode.
    body = json.dumps({k: doc[k] for k in ("entrypoints", "previews")}, sort_keys=True)
    doc["surfaceHash"] = hashlib.sha256(body.encode()).hexdigest()[:16]
    return doc


def main():
    doc = build()
    text = json.dumps(doc, indent=1, sort_keys=False) + "\n"
    if "--write" in sys.argv:
        io.open(OUT, "w", encoding="utf8").write(text)
        print(f"wrote Deploy/TALOS-ABI.json -- {len(doc['entrypoints'])} entrypoints, "
              f"{len(doc['previews'])} previews, {len(doc['previewFor'])} paired "
              f"(surface {doc['surfaceHash']})")
        return 0
    if "--check" in sys.argv:
        if not os.path.exists(OUT):
            print("TALOS ABI: Deploy/TALOS-ABI.json is absent. Run --write.")
            return 1
        if io.open(OUT, encoding="utf8").read() != text:
            print("TALOS ABI: Deploy/TALOS-ABI.json is STALE against the Pact sources.\n"
                  "  A renamed or re-signatured entrypoint that is not carried into the ABI "
                  "reaches consumers as\n  'no such member', which `try` cannot catch and which "
                  "they render as missing data.\n  Regenerate: python3 REPL/tools/_talosabi.py "
                  "--write")
            return 1
        print(f"TALOS ABI: clean -- {len(doc['entrypoints'])} entrypoints, "
              f"{len(doc['previews'])} previews, surface {doc['surfaceHash']}")
        return 0
    print(__doc__)
    return 0


if __name__ == "__main__":
    sys.exit(main())
